import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1778523139619 implements MigrationInterface {
    name = 'AutoMigration1778523139619'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "auth" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_b54f616411ef3824f6a5c06ea46" UNIQUE ("email"), CONSTRAINT "PK_7e416cf6172bc5aec04244f6459" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "name" character varying NOT NULL, "price" numeric NOT NULL, "gymId" uuid, CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PRODUCT_GYM" ON "product" ("gymId") `);
        await queryRunner.query(`CREATE TABLE "gym" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "name" character varying NOT NULL, "address" character varying NOT NULL, "city" character varying NOT NULL, "country" character varying NOT NULL, "documents" text array, "isActive" boolean NOT NULL DEFAULT true, "ownerId" uuid, CONSTRAINT "PK_5ec4eaae24cb81794abbd1af787" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_GYM_CITY" ON "gym" ("city") `);
        await queryRunner.query(`CREATE INDEX "IDX_GYM_NAME" ON "gym" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."gym_members_role_enum" AS ENUM('owner', 'admin', 'manager', 'trainer', 'member')`);
        await queryRunner.query(`CREATE TABLE "gym_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "role" "public"."gym_members_role_enum" NOT NULL DEFAULT 'member', "isActive" boolean NOT NULL DEFAULT true, "userId" uuid, "gymId" uuid, CONSTRAINT "PK_c8ec596e819911e06aa04b54b8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_systemrole_enum" AS ENUM('super_admin', 'user')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "username" character varying NOT NULL, "systemRole" "public"."user_systemrole_enum" NOT NULL DEFAULT 'user', CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_USER_USERNAME" ON "user" ("username") `);
        await queryRunner.query(`CREATE TABLE "membership_package" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "name" character varying NOT NULL, "price" numeric NOT NULL, "durationDays" integer NOT NULL, "gymId" uuid, CONSTRAINT "PK_64022fa477eb181bfc0dcdfa82f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PACKAGE_GYM" ON "membership_package" ("gymId") `);
        await queryRunner.query(`CREATE TABLE "user_membership" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "userId" uuid, "gymId" uuid NOT NULL, "packageId" uuid, CONSTRAINT "PK_79d3d7350ae33ad6fe1743df86c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_USER_MEMBERSHIP_ACTIVE" ON "user_membership" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_MEMBERSHIP_GYM" ON "user_membership" ("gymId") `);
        await queryRunner.query(`CREATE INDEX "IDX_USER_MEMBERSHIP_USER" ON "user_membership" ("userId") `);
        await queryRunner.query(`CREATE TABLE "sale" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "totalAmount" numeric NOT NULL, "gymId" uuid, "soldById" uuid, CONSTRAINT "PK_d03891c457cbcd22974732b5de2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_SALE_USER" ON "sale" ("soldById") `);
        await queryRunner.query(`CREATE INDEX "IDX_SALE_GYM" ON "sale" ("gymId") `);
        await queryRunner.query(`CREATE TABLE "sale_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "quantity" integer NOT NULL, "price" numeric NOT NULL, "saleId" uuid, "productId" uuid, CONSTRAINT "PK_439a57a4a0d130329d3d2e671b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_SALE_ITEM_PRODUCT" ON "sale_item" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_SALE_ITEM_SALE" ON "sale_item" ("saleId") `);
        await queryRunner.query(`CREATE TABLE "pay_roll" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_06eaf0aed4d19d782fbf36cc031" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "amount" numeric NOT NULL, "method" "public"."payment_method_enum" NOT NULL, "status" "public"."payment_status_enum" NOT NULL DEFAULT 'pending', "type" "public"."payment_type_enum" NOT NULL, "referenceId" character varying, "date" TIMESTAMP NOT NULL, "userId" uuid, "gymId" uuid, CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PAYMENT_STATUS" ON "payment" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAYMENT_TYPE" ON "payment" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAYMENT_GYM" ON "payment" ("gymId") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAYMENT_USER" ON "payment" ("userId") `);
        await queryRunner.query(`CREATE TABLE "leave" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "reason" character varying NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "status" "public"."leave_status_enum" NOT NULL DEFAULT 'pending', "userId" uuid, "gymId" uuid, CONSTRAINT "PK_501f6ea368365d2a40b1660e16b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_LEAVE_GYM_DATE" ON "leave" ("gymId", "startDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_LEAVE_USER_STATUS" ON "leave" ("userId", "status") `);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "productId" uuid, "gymId" uuid, CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_INVENTORY_GYM" ON "inventory" ("gymId") `);
        await queryRunner.query(`CREATE INDEX "IDX_INVENTORY_PRODUCT" ON "inventory" ("productId") `);
        await queryRunner.query(`CREATE TABLE "employee" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "position" character varying NOT NULL, "salary" numeric NOT NULL, "userId" uuid, "gymId" uuid, CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_At" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL, "checkIn" TIMESTAMP NOT NULL, "checkOut" TIMESTAMP, "userId" uuid, "gymId" uuid, CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ATTENDANCE_USER_GYM_DATE" ON "attendance" ("userId", "gymId", "checkIn") `);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_d27433a00d4d057f49c4897dadf" FOREIGN KEY ("gymId") REFERENCES "gym"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym" ADD CONSTRAINT "FK_2d945c0c256305baa1db3121308" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym_members" ADD CONSTRAINT "FK_17a26d20964ea7670b28d10f389" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gym_members" ADD CONSTRAINT "FK_9d5bff6b44782bb5cedf9abce33" FOREIGN KEY ("gymId") REFERENCES "gym"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_package" ADD CONSTRAINT "FK_8baad3e7895f652e32fdb6da99c" FOREIGN KEY ("gymId") REFERENCES "gym"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_membership" ADD CONSTRAINT "FK_f0e577f1e2f66348bd10796d004" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_membership" ADD CONSTRAINT "FK_09732a764759448252a74bb05bf" FOREIGN KEY ("gymId") REFERENCES "gym"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_membership" ADD CONSTRAINT "FK_05a350459266c94686fc3fac6c6" FOREIGN KEY ("packageId") REFERENCES "membership_package"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_bfabc440953dd67a28de240ec2b" FOREIGN KEY ("gymId") REFERENCES "gym"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_37e87b5068c1cc6e0a00bbd194c" FOREIGN KEY ("soldById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_item" ADD CONSTRAINT "FK_59208ed392dd61056abbcf1482e" FOREIGN KEY ("saleId") REFERENCES "sale"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_item" ADD CONSTRAINT "FK_d4361a12f11a57a6cf2a2ee6ac9" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_b046318e0b341a7f72110b75857" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_0ac87d070d7ab61a5bfd5bf4834" FOREIGN KEY ("gymId") REFERENCES "gym"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave" ADD CONSTRAINT "FK_9fb20081bf48840a16e0d33d14e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave" ADD CONSTRAINT "FK_1e1496f076fd00fa0ee44a897aa" FOREIGN KEY ("gymId") REFERENCES "gym"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_c8622e1e24c6d054d36e8824490" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_a40da1e4ea6fe3e4e89638687cf" FOREIGN KEY ("gymId") REFERENCES "gym"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_f4b0d329c4a3cf79ffe9d565047" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_5972e0d0797f75192e59834d430" FOREIGN KEY ("gymId") REFERENCES "gym"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_466e85b813d871bfb693f443528" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_1b89d26b8081976851f3cc13209" FOREIGN KEY ("gymId") REFERENCES "gym_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_1b89d26b8081976851f3cc13209"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_466e85b813d871bfb693f443528"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_5972e0d0797f75192e59834d430"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_f4b0d329c4a3cf79ffe9d565047"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_a40da1e4ea6fe3e4e89638687cf"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_c8622e1e24c6d054d36e8824490"`);
        await queryRunner.query(`ALTER TABLE "leave" DROP CONSTRAINT "FK_1e1496f076fd00fa0ee44a897aa"`);
        await queryRunner.query(`ALTER TABLE "leave" DROP CONSTRAINT "FK_9fb20081bf48840a16e0d33d14e"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_0ac87d070d7ab61a5bfd5bf4834"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_b046318e0b341a7f72110b75857"`);
        await queryRunner.query(`ALTER TABLE "sale_item" DROP CONSTRAINT "FK_d4361a12f11a57a6cf2a2ee6ac9"`);
        await queryRunner.query(`ALTER TABLE "sale_item" DROP CONSTRAINT "FK_59208ed392dd61056abbcf1482e"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_37e87b5068c1cc6e0a00bbd194c"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_bfabc440953dd67a28de240ec2b"`);
        await queryRunner.query(`ALTER TABLE "user_membership" DROP CONSTRAINT "FK_05a350459266c94686fc3fac6c6"`);
        await queryRunner.query(`ALTER TABLE "user_membership" DROP CONSTRAINT "FK_09732a764759448252a74bb05bf"`);
        await queryRunner.query(`ALTER TABLE "user_membership" DROP CONSTRAINT "FK_f0e577f1e2f66348bd10796d004"`);
        await queryRunner.query(`ALTER TABLE "membership_package" DROP CONSTRAINT "FK_8baad3e7895f652e32fdb6da99c"`);
        await queryRunner.query(`ALTER TABLE "gym_members" DROP CONSTRAINT "FK_9d5bff6b44782bb5cedf9abce33"`);
        await queryRunner.query(`ALTER TABLE "gym_members" DROP CONSTRAINT "FK_17a26d20964ea7670b28d10f389"`);
        await queryRunner.query(`ALTER TABLE "gym" DROP CONSTRAINT "FK_2d945c0c256305baa1db3121308"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_d27433a00d4d057f49c4897dadf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ATTENDANCE_USER_GYM_DATE"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TABLE "employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INVENTORY_PRODUCT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_INVENTORY_GYM"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_LEAVE_USER_STATUS"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_LEAVE_GYM_DATE"`);
        await queryRunner.query(`DROP TABLE "leave"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAYMENT_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAYMENT_GYM"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAYMENT_TYPE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAYMENT_STATUS"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "pay_roll"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SALE_ITEM_SALE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SALE_ITEM_PRODUCT"`);
        await queryRunner.query(`DROP TABLE "sale_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SALE_GYM"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SALE_USER"`);
        await queryRunner.query(`DROP TABLE "sale"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_MEMBERSHIP_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_MEMBERSHIP_GYM"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_MEMBERSHIP_ACTIVE"`);
        await queryRunner.query(`DROP TABLE "user_membership"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PACKAGE_GYM"`);
        await queryRunner.query(`DROP TABLE "membership_package"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_USERNAME"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_systemrole_enum"`);
        await queryRunner.query(`DROP TABLE "gym_members"`);
        await queryRunner.query(`DROP TYPE "public"."gym_members_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GYM_NAME"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_GYM_CITY"`);
        await queryRunner.query(`DROP TABLE "gym"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PRODUCT_GYM"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "auth"`);
    }

}
