import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1779815237528 implements MigrationInterface {
    name = 'AutoMigration1779815237528'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auth" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "gym_branch" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "gym_branch" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "gym" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "gym" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "gym_members" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "gym_members" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "membership_package" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "membership_package" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "user_membership" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "user_membership" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "sale_item" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "sale_item" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "pay_roll" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "pay_roll" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "leave" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "leave" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "created_At"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "updated_At"`);
        await queryRunner.query(`ALTER TABLE "auth" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auth" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "product" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "gym_branch" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "gym_branch" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "gym" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "gym" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "gym_members" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "gym_members" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "membership_package" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "membership_package" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_membership" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_membership" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_item" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_item" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pay_roll" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pay_roll" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "leave" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "leave" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "leave" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "leave" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "pay_roll" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "pay_roll" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sale_item" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sale_item" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_membership" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_membership" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "membership_package" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "membership_package" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "gym_members" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "gym_members" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "gym" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "gym" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "gym_branch" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "gym_branch" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "auth" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_roll" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pay_roll" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sale_item" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sale_item" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sale" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sale" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_membership" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_membership" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "membership_package" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "membership_package" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gym_members" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gym_members" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gym" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gym" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gym_branch" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gym_branch" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth" ADD "updated_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth" ADD "created_At" TIMESTAMP WITH TIME ZONE NOT NULL`);
    }

}
