// src/auth/dto/create-role.dto.ts

import {
  IsOptional, // Marks the field as optional.
  IsString, // Ensures the value is a string.
  MaxLength, // Enforces a maximum length.
  MinLength, // Enforces a minimum length.
} from 'class-validator';

import { Transform } from 'class-transformer';

/**
 * Body shape for POST /api/roles — create a new role.
 *
 * Used by RolesController.create().
 *
 * Example body:
 *   {
 *     "name": "Manager",
 *     "description": "Operations manager"
 *   }
 *
 * What's NOT here:
 *   • companyId  → read from the X-Company-Id header, not the body.
 *                 Never trust the client to say which company they're in.
 *   • id, createdAt, etc. → auto-generated by the DB.
 */
export class CreateRoleDto {
  /**
   * Role name — required.
   * Must be 2–80 characters.
   * Trimmed of whitespace before validation.
   */
  @IsString()
  @MinLength(2, { message: 'Role name must be at least 2 characters' })
  @MaxLength(80, { message: 'Role name must be at most 80 characters' })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  name: string;

  /**
   * Optional description.
   * No length limit — it's just for humans.
   * Empty string is converted to null.
   */
  @IsOptional()
  @IsString()
  @Transform(({ value }) => {
    if (typeof value !== 'string') return value;
    const trimmed = value.trim();
    return trimmed === '' ? null : trimmed;
  })
  description?: string | null;
}
