export const successMessage = {
  login: 'Login successful',
  logout: 'Logout successful',
  register: 'Registration successful',
  userCreate: 'User created successfully',
  userUpdate: 'User updated successfully',
  gymCreate: 'Gym created successfully',
  gymUpdate: 'Gym updated successfully',
  employeeCreate: 'Employee added successfully',
  employeeUpdate: 'Employee updated successfully',
  membershipCreate: 'Membership created successfully',
  membershipUpdate: 'Membership updated successfully',
  paymentSuccess: 'Payment processed successfully',
  attendanceMarked: 'Attendance marked successfully',
  leaveRequested: 'Leave request submitted successfully',
  payrollProcessed: 'Payroll processed successfully',
  notificationSent: 'Notification sent successfully',
};

export const errorMessage = {
  invalidCredentials: 'Invalid credentials',
  userNotFound: 'User not found',
  authFailed: 'Authentication failed',
  unauthorized: 'You are not authorized to perform this action',
  gymNotFound: 'Gym not found',
  employeeNotFound: 'Employee not found',
  membershipNotFound: 'Membership not found',
  paymentFailed: 'Payment processing failed',
  attendanceAlreadyMarked: 'Attendance already marked',
  leaveDenied: 'Leave request denied',
  payrollError: 'Error processing payroll',
  notificationFailed: 'Failed to send notification',
  serverError: 'Internal server error',
  validationError: 'Validation failed',
};
