export enum ROLEENUM {
  SUPER_ADMIN = "SUPER_ADMIN",
  GYM_OWNER = "GYM_OWNER",
  STAFF = "STAFF",
  MEMBER = "MEMBER",
}

export enum SUBSCRIPTIONSTATUSENUM {
  TRIAL_ACTIVE = "TRIAL_ACTIVE",
  TRIAL_EXPIRED = "TRIAL_EXPIRED",
  PLAN_ACTIVE = "PLAN_ACTIVE",
  PLAN_EXPIRED = "PLAN_EXPIRED",
  NO_PLAN = "NO_PLAN",
}
